import { StyleSheet } from 'react-native';
import * as FONT from 'src/assets/fonts';
import * as COLOR from 'src/constants/colors';

export default styles = StyleSheet.create({
  container: {
    height: '100%',
    width: '100%',
    backgroundColor: COLOR.THEME.WHITE,
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  dataContainer: {
    marginBottom: 130,
    alignSelf: 'center',
  },
  containStyle: {
    marginBottom: 100,
  },
  cellContainer: {
    margin: 10,
    backgroundColor: COLOR.THEME.CEll_BG,
    flexDirection: 'column',
    borderRadius: 3,
  },
  cellTitle: {
    color: COLOR.THEME.BLACK,
    fontFamily: FONT.ROBOTO,
    paddingHorizontal: 10,
    fontWeight: 'bold',
    fontSize: 18,
    marginTop: 15,
  },
  cellDesc: {
    fontFamily: FONT.ROBOTO,
    color: COLOR.THEME.LIGHT_GRAY,
    paddingHorizontal: 10,
    fontSize: 14,
    marginVertical: 10,
  },
  cellTime: {
    fontFamily: FONT.ROBOTO,
    fontStyle: 'italic',
    color: COLOR.THEME.LIGHT_GRAY,
    paddingHorizontal: 10,
    fontSize: 14,
    marginBottom: 20,
    alignSelf: 'flex-end',
  },
  buttonContainer: {
    justifyContent: 'center',
    width: '100%',
    height: 120,
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
  },
  popupView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  toucableButton: {
    height: 40,
    width: '50%',
    backgroundColor: COLOR.THEME.GREEN,
    borderRadius: 4,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonTitle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
  },
  modalOverlay: {
    height: '100%',
    width: '100%',
    backgroundColor: '#00000095',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: 'white',
    width: '90%',
    alignSelf: 'center',
    borderRadius: 4,
    paddingBottom: 20,
  },
  closeContainer: {
    height: 30,
    width: 30,
    position: 'absolute',
    top: 10,
    right: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyboardAwareL: {
    flex: 1,
  },
  modalTitle: {
    fontFamily: FONT.ROBOTO,
    alignSelf: 'center',
    marginTop: 35,
    fontSize: 17,
    fontWeight: 'bold',
  },
  modalDesc: {
    fontFamily: FONT.ROBOTO,
    alignSelf: 'center',
    marginTop: 20,
    fontSize: 14,
    paddingHorizontal: 15,
    textAlign: 'center',
    color: COLOR.THEME.LIGHT_GRAY,
  },
  modalSep: {
    height: 0.5,
    width: '90%',
    backgroundColor: COLOR.THEME.SEPARETOR,
    alignSelf: 'center',
    marginVertical: 30,
  },
  useCodeText: {
    fontFamily: FONT.ROBOTO,
    alignSelf: 'center',
    fontSize: 14,
    paddingHorizontal: 15,
    textAlign: 'center',
    color: COLOR.THEME.BLACK,
  },
  codeText: {
    fontFamily: FONT.ROBOTO,
    alignSelf: 'center',
    marginTop: 5,
    fontSize: 14,
    fontWeight: 'bold',
  },
  codeDesc: {
    fontFamily: FONT.ROBOTO,
    alignSelf: 'center',
    fontSize: 14,
    paddingHorizontal: 15,
    marginTop: 5,
    marginBottom: 30,
    textAlign: 'center',
    color: COLOR.THEME.BLACK,
  },
  closeIcon: {
    height: 30,
    width: 30,
  },
});
