export const GET_DEFAULT_REQUEST = 'GET_DEFAULT_REQUEST';
export const GET_DEFAULT_SUCCESS = 'GET_DEFAULT_SUCCESS';
export const GET_DEFAULT_ERROR = 'GET_DEFAULT_ERROR';
export const DEFAULT_DATA_CLEAR = 'DEFAULT_DATA_CLEAR';

//get types list
export const GET_TYPES_REQUEST = 'GET_TYPES_REQUEST';
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export const GET_TYPES_ERROR = 'GET_TYPES_ERROR';

//get saved calculation
export const GET_SAVED_REQUEST = 'GET_SAVED_REQUEST';
export const GET_SAVED_SUCCESS = 'GET_SAVED_SUCCESS';
export const GET_SAVED_ERROR = 'GET_SAVED_ERROR';

//get saved detail calculation
export const GET_SAVED_DETAIL_REQUEST = 'GET_SAVED_DETAIL_REQUEST';
export const GET_SAVED_DETAIL_SUCCESS = 'GET_SAVED_DETAIL_SUCCESS';
export const GET_SAVED_DETAIL_ERROR = 'GET_SAVED_DETAIL_ERROR';

//COUNTY
//get county
export const GET_COUNTY_REQUEST = 'GET_COUNTY_REQUEST';
export const GET_COUNTY_SUCCESS = 'GET_COUNTY_SUCCESS';
export const GET_COUNTY_ERROR = 'GET_COUNTY_ERROR';

//save calculation
export const SAVE_CALCULATION_REQUEST = 'SAVE_CALCULATION_REQUEST';
export const SAVE_CALCULATION_SUCCESS = 'SAVE_CALCULATION_SUCCESS';
export const SAVE_CALCULATION_ERROR = 'SAVE_CALCULATION_ERROR';
export const SAVE_CALCULATION_DATA_CLEAR = 'SAVE_CALCULATION_DATA_CLEAR';

//FHA calculation
export const FHA_CALCULATION_REQUEST = 'FHA_CALCULATION_REQUEST';
export const FHA_CALCULATION_SUCCESS = 'FHA_CALCULATION_SUCCESS';
export const FHA_CALCULATION_ERROR = 'FHA_CALCULATION_ERROR';
export const FHA_CALCULATION_DATA_CLEAR = 'FHA_CALCULATION_DATA_CLEAR';

//conventional calculation
export const CONVENTIONAL_CALCULATION_REQUEST =
  'CONVENTIONAL_CALCULATION_REQUEST';
export const CONVENTIONAL_CALCULATION_SUCCESS =
  'CONVENTIONAL_CALCULATION_SUCCESS';
export const CONVENTIONAL_CALCULATION_ERROR = 'CONVENTIONAL_CALCULATION_ERROR';

//jumbo calculation
export const JUMBO_CALCULATION_REQUEST = 'JUMBO_CALCULATION_REQUEST';
export const JUMBO_CALCULATION_SUCCESS = 'JUMBO_CALCULATION_SUCCESS';
export const JUMBO_CALCULATION_ERROR = 'JUMBO_CALCULATION_ERROR';

//usda calculation
export const USDA_CALCULATION_REQUEST = 'USDA_CALCULATION_REQUEST';
export const USDA_CALCULATION_SUCCESS = 'USDA_CALCULATION_SUCCESS';
export const USDA_CALCULATION_ERROR = 'USDA_CALCULATION_ERROR';

//va calculation
export const VA_CALCULATION_REQUEST = 'VA_CALCULATION_REQUEST';
export const VA_CALCULATION_SUCCESS = 'VA_CALCULATION_SUCCESS';
export const VA_CALCULATION_ERROR = 'VA_CALCULATION_ERROR';

//affordability calculation
export const AFD_CALCULATION_REQUEST = 'AFD_CALCULATION_REQUEST';
export const AFD_CALCULATION_SUCCESS = 'AFD_CALCULATION_SUCCESS';
export const AFD_CALCULATION_ERROR = 'AFD_CALCULATION_ERROR';

//Refinance

//FHA calculation
export const FHA_REFINANCE_CALCULATION_REQUEST =
  'FHA_REFINANCE_CALCULATION_REQUEST';
export const FHA_REFINANCE_CALCULATION_SUCCESS =
  'FHA_REFINANCE_CALCULATION_SUCCESS';
export const FHA_REFINANCE_CALCULATION_ERROR =
  'FHA_REFINANCE_CALCULATION_ERROR';

//Convetional  calculation
export const CONVETIONAL_REFINANCE_CALCULATION_REQUEST =
  'CONVETIONAL_REFINANCE_CALCULATION_REQUEST';
export const CONVETIONAL_REFINANCE_CALCULATION_SUCCESS =
  'CONVETIONAL_REFINANCE_CALCULATION_SUCCESS';
export const CONVETIONAL_REFINANCE_CALCULATION_ERROR =
  'CONVETIONAL_REFINANCE_CALCULATION_ERROR';

//Jumbo  calculation
export const JUMBO_REFINANCE_CALCULATION_REQUEST =
  'JUMBO_REFINANCE_CALCULATION_REQUEST';
export const JUMBO_REFINANCE_CALCULATION_SUCCESS =
  'JUMBO_REFINANCE_CALCULATION_SUCCESS';
export const JUMBO_REFINANCE_CALCULATION_ERROR =
  'JUMBO_REFINANCE_CALCULATION_ERROR';

//usda  calculation
export const USDA_REFINANCE_CALCULATION_REQUEST =
  'USDA_REFINANCE_CALCULATION_REQUEST';
export const USDA_REFINANCE_CALCULATION_SUCCESS =
  'USDA_REFINANCE_CALCULATION_SUCCESS';
export const USDA_REFINANCE_CALCULATION_ERROR =
  'USDA_REFINANCE_CALCULATION_ERROR';

//va  calculation
export const VA_REFINANCE_CALCULATION_REQUEST =
  'VA_REFINANCE_CALCULATION_REQUEST';
export const VA_REFINANCE_CALCULATION_SUCCESS =
  'VA_REFINANCE_CALCULATION_SUCCESS';
export const VA_REFINANCE_CALCULATION_ERROR = 'VA_REFINANCE_CALCULATION_ERROR';

//should i refinance calculation
export const SIR_CALCULATION_REQUEST = 'SIR_CALCULATION_REQUEST';
export const SIR_CALCULATION_SUCCESS = 'SIR_CALCULATION_SUCCESS';
export const SIR_CALCULATION_ERROR = 'SIR_CALCULATION_ERROR';

//delete saved calculation
export const DELETE_CALCULATION_REQUEST = 'DELETE_CALCULATION_REQUEST';
export const DELETE_CALCULATION_SUCCESS = 'DELETE_CALCULATION_SUCCESS';
export const DELETE_CALCULATION_ERROR = 'DELETE_CALCULATION_ERROR';
