//callback Request
export const CALLBACK_REQUEST_REQUEST = 'CALLBACK_REQUEST_REQUEST';
export const CALLBACK_REQUEST_SUCCESS = 'CALLBACK_REQUEST_SUCCESS';
export const CALLBACK_REQUEST_ERROR = 'CALLBACK_REQUEST_ERROR';
export const CALLBACK_REQUEST_CLEAR = "CALLBACK_REQUEST_CLEAR";