export const SET_SETTING_OPENS = 'SET_SETTING_OPENS';
export const SCAN_REDIRECT = 'SCAN_REDIRECT';
export const SHOW_VALIDATION_ALERT = 'SHOW_VALIDATION_ALERT';
export const CLOSE_VALIDATION_ALERT = 'CLOSE_VALIDATION_ALERT';
export const CLEAR_REDIRECT = 'CLEAR_REDIRECT';
export const SET_CUSTOM_LINK = 'SET_CUSTOM_LINK';

export const SET_SCAN_IMAGES = 'SET_SCAN_IMAGES';
export const CLEAR_SCAN_IMAGES = 'CLEAR_SCAN_IMAGES';

export const SET_FILE_NAME = 'SET_FILE_NAME';

export const SET_THEME = 'SET_THEME';
export const SET_DEFAULT_THEME = 'SET_DEFAULT_THEME';
export const GET_THEME = 'GET_THEME';

//loader
export const SET_LOADER_TRUE = 'SET_LOADER_TRUE';
export const CLEAR_LOADER = 'CLEAR_LOADER';
export const SET_CURRENT_DATE = 'SET_CURRENT_DATE';

export const SET_GUEST = 'SET_GUEST';
