//get color scheme
export const GET_COLOR_SCHEME_REQUEST = 'GET_COLOR_SCHEME_REQUEST';
export const GET_COLOR_SCHEME_SUCCESS = 'GET_COLOR_SCHEME_SUCCESS';
export const GET_COLOR_SCHEME_ERROR = 'GET_COLOR_SCHEME_ERROR';


//get main list
export const GET_MAIN_LIST_REQUEST = 'GET_MAIN_LIST_REQUEST';
export const GET_MAIN_LIST_SUCCESS = 'GET_MAIN_LIST_SUCCESS';
export const GET_MAIN_LIST_ERROR = 'GET_MAIN_LIST_ERROR';
export const SET_TABBAR_TABS = 'SET_TABBAR_TABS';

//get lo officers list
export const GET_LOOFFICER_REQUEST = 'GET_LOOFFICER_REQUEST';
export const GET_LOOFFICER_SUCCESS = 'GET_LOOFFICER_SUCCESS';
export const GET_LOOFFICER_ERROR = 'GET_LOOFFICER_ERROR';

//get lo officer details
export const GET_DETAIL_REQUEST = 'GET_DETAIL_REQUEST';
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS';
export const GET_DETAIL_ERROR = 'GET_DETAIL_ERROR';

//get assigned lo
export const GET_ASSIGNED_LO_REQUEST = 'GET_ASSIGNED_LO_REQUEST';
export const GET_ASSIGNED_LO_SUCCESS = 'GET_ASSIGNED_LO_SUCCESS';
export const GET_ASSIGNED_LO_ERROR = 'GET_ASSIGNED_LO_ERROR';

//assign lo
export const ASSIGN_LO_REQUEST = 'ASSIGN_LO_REQUEST';
export const ASSIGN_LO_SUCCESS = 'SASSIGN_LO_SUCCESS';
export const ASSIGN_LO_ERROR = 'ASSIGN_LO_ERROR';
export const ASSIGN_LO_CLEAR = 'ASSIGN_LO_CLEAR';

export const GET_DASHBOARD_LIST_REQUEST = 'GET_DASHBOARD_LIST_REQUEST';
export const GET_DASHBOARD_LIST_SUCCESS = 'GET_DASHBOARD_LIST_SUCCESS';
export const GET_DASHBOARD_LIST_ERROR = 'GET_DASHBOARD_LIST_ERROR';