export const GET_GUIDE_LIST_REQUEST = 'GET_GUIDE_LIST_REQUEST';
export const GET_GUIDE_LIST_SUCCESS = 'GET_GUIDE_LIST_SUCCESS';
export const GET_GUIDE_LIST_ERROR = 'GET_GUIDE_LIST_ERROR';


export const GET_LOAN_PROGRAM_REQUEST = 'GET_LOAN_PROGRAM_REQUEST';
export const GET_LOAN_PROGRAM_SUCCESS = 'GET_LOAN_PROGRAM_SUCCESS';
export const GET_LOAN_PROGRAM_ERROR = 'GET_LOAN_PROGRAM_ERROR';

export const GET_LOAN_PROGRAM_DETAIL_REQUEST = 'GET_LOAN_PROGRAM_DETAIL_REQUEST';
export const GET_LOAN_PROGRAM_DETAIL_SUCCESS = 'GET_LOAN_PROGRAM_DETAIL_SUCCESS';
export const GET_LOAN_PROGRAM_DETAIL_ERROR = 'GET_LOAN_PROGRAM_DETAIL_ERROR';

//get learning center
export const GET_LEARNING_CENTER_REQUEST = 'GET_LEARNING_CENTER_REQUEST';
export const GET_LEARNING_CENTER_SUCCESS = 'GET_LEARNING_CENTER_SUCCESS';
export const GET_LEARNING_CENTER_ERROR = 'GET_LEARNING_CENTER_ERROR';

//get learning center Detail
export const GET_LEARNING_CENTER_DETAIL_REQUEST = 'GET_LEARNING_CENTER_DETAIL_REQUEST';
export const GET_LEARNING_CENTER_DETAIL_SUCCESS = 'GET_LEARNING_CENTER_DETAIL_SUCCESS';
export const GET_LEARNING_CENTER_DETAIL_ERROR = 'GET_LEARNING_CENTER_DETAIL_ERROR';


//get checklist
export const GET_CHECKLIST_REQUEST = 'GET_CHECKLIST_REQUEST';
export const GET_CHECKLIST_SUCCESS = 'GET_CHECKLIST_SUCCESS';
export const GET_CHECKLIST_ERROR = 'GET_CHECKLIST_ERROR';


//get privacy
export const GET_PRIVACY_REQUEST = 'GET_PRIVACY_REQUEST';
export const GET_PRIVACY_SUCCESS = 'GET_PRIVACY_SUCCESS';
export const GET_PRIVACY_ERROR = 'GET_PRIVACY_ERROR';

//get disclaimer
export const GET_DISCLAIMER_REQUEST = 'GET_DISCLAIMER_REQUEST';
export const GET_DISCLAIMER_SUCCESS = 'GET_DISCLAIMER_SUCCESS';
export const GET_DISCLAIMER_ERROR = 'GET_DISCLAIMER_ERROR';


//update checklist
export const UPDATE_CHECKLIST_REQUEST = 'UPDATE_CHECKLIST_REQUEST';
export const UPDATE_CHECKLIST_SUCCESS = 'UPDATE_CHECKLIST_SUCCESS';
export const UPDATE_CHECKLIST_ERROR = 'UPDATE_CHECKLIST_ERROR';


//get glossaryList
export const GET_GLOSSARYLIST_REQUEST = 'GET_GLOSSARYLIST_REQUEST';
export const GET_GLOSSARYLIST_SUCCESS = 'GET_GLOSSARYLIST_SUCCESS';
export const GET_GLOSSARYLIST_ERROR = 'GET_GLOSSARYLIST_ERROR';