export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CHANGE_PASSWORD_DATA_CLEAR = 'CHANGE_PASSWORD_DATA_CLEAR';
//SAVE_BORROWER_PROFILE

export const SAVE_BORROWER_PROFILE_REQUEST = 'SAVE_BORROWER_PROFILE_REQUEST';
export const SAVE_BORROWER_PROFILE_SUCCESS = 'SAVE_BORROWER_PROFILE_SUCCESS';
export const SAVE_BORROWER_PROFILE_ERROR = 'SAVE_BORROWER_PROFILE_ERROR';
export const BORROWER_PROFILE_DATA_CLEAR = 'BORROWER_PROFILE_DATA_CLEAR';
//SAVE_LO_PROFILE

export const SAVE_LO_PROFILE_REQUEST = 'SAVE_LO_PROFILE_REQUEST';
export const SAVE_LO_PROFILE_SUCCESS = 'SAVE_LO_PROFILE_SUCCESS';
export const SAVE_LO_PROFILE_ERROR = 'SAVE_LO_PROFILE_ERROR';
export const LO_PROFILE_DATA_CLEAR = 'LO_PROFILE_DATA_CLEAR';

// /GET_NOTIFICATION_SUCCESS
export const GET_NOTIFICATION_SETTING_REQUEST =
  'GET_NOTIFICATION_SETTING_REQUEST';
export const GET_NOTIFICATION_SETTING_SUCCESS =
  'GET_NOTIFICATION_SETTING_SUCCESS';
export const GET_NOTIFICATION_SETTING_ERROR = 'GET_NOTIFICATION_SETTING_ERROR';

// /Save_NOTIFICATION_SUCCESS
export const SAVE_NOTIFICATION_SETTING_REQUEST =
  'SAVE_NOTIFICATION_SETTING_REQUEST';
export const SAVE_NOTIFICATION_SETTING_SUCCESS =
  'SAVE_NOTIFICATION_SETTING_SUCCESS';
export const SAVE_NOTIFICATION_SETTING_ERROR =
  'SAVE_NOTIFICATION_SETTING_ERROR';

//REFER_DEEP_LINK
export const REFER_DEEP_LINK_REQUEST = 'REFER_DEEP_LINK_REQUEST';
export const REFER_DEEP_LINK_SUCCESS = 'REFER_DEEP_LINK_SUCCESS';
export const REFER_DEEP_LINK_ERROR = 'REFER_DEEP_LINK_ERROR';

//Get Chat ID
export const GET_CHAT_ID_REQUEST = 'GET_CHAT_ID_REQUEST';
export const GET_CHAT_ID_SUCCESS = 'GET_CHAT_ID_SUCCESS';
export const GET_CHAT_ID_ERROR = 'GET_CHAT_ID_ERROR';

export const CHAT_ID_DATA_CLEAR = 'CHAT_ID_DATA_CLEAR';

//Get Borrowers
export const GET_BORROWERS_REQUEST = 'GET_BORROWERS_REQUEST';
export const GET_BORROWERS_SUCCESS = 'GET_BORROWERS_SUCCESS';
export const GET_BORROWERS_ERROR = 'GET_BORROWERS_ERROR';

// /Save chat document
export const SAVE_CHAT_DOCUMENT_REQUEST = 'SAVE_CHAT_DOCUMENT_REQUEST';
export const SAVE_CHAT_DOCUMENT_SUCCESS = 'SAVE_CHAT_DOCUMENT_SUCCESS';
export const SAVE_CHAT_DOCUMENT_ERROR = 'SAVE_CHAT_DOCUMENT_ERROR';

//update email
export const UPADTE_EMAIL_REQUEST = 'UPADTE_EMAIL_REQUEST';
export const UPADTE_EMAIL_SUCCESS = 'UPADTE_EMAIL_SUCCESS';
export const UPADTE_EMAIL_ERROR = 'UPADTE_EMAIL_ERROR';
export const CLEAR_UPDATE_EMAIL = 'CLEAR_UPDATE_EMAIL';

//Get LO Dashboard list
export const GET_LO_DASHBOARD_LIST_REQUEST = 'GET_LO_DASHBOARD_LIST_REQUEST';
export const GET_LO_DASHBOARD_LIST_SUCCESS = 'GET_LO_DASHBOARD_LIST_SUCCESS';
export const GET_LO_DASHBOARD_LIST_ERROR = 'GET_LO_DASHBOARD_LIST_ERROR';

//NOTIFICATION
export const GET_NOTIFICATION_LIST_REQUEST = 'GET_NOTIFICATION_LIST_REQUEST';
export const GET_NOTIFICATION_LIST_SUCCESS = 'GET_NOTIFICATION_LIST_SUCCESS';
export const GET_NOTIFICATION_LIST_ERROR = 'GET_NOTIFICATION_LIST_ERROR';

//DEVICE_TOKEN
export const SAVE_DEVICE_TOKEN_REQUEST = 'SAVE_DEVICE_TOKEN_REQUEST';
export const SAVE_DEVICE_TOKEN_SUCCESS = 'SAVE_DEVICE_TOKEN_SUCCESS';
export const SAVE_DEVICE_TOKEN_ERROR = 'SAVE_DEVICE_TOKEN_ERROR';
