import { StyleSheet } from 'react-native';
import * as FONT from 'src/assets/fonts';
import * as COLOR from 'src/constants/colors';
import * as CONSTANT from 'src/constants/constant';
const optionContainerWidth = CONSTANT.SCREEN_WIDTH - 80;
const optionWidth = optionContainerWidth / 6.5;
const marginHori = CONSTANT.SCREEN_WIDTH / 6;

const styles = StyleSheet.create({
  container: {
    height: '100%',
    width: '100%',
    backgroundColor: COLOR.THEME.WHITE,
    flexDirection: 'column',
  },
  dataContainer: {
    marginBottom: 130,
  },
  containStyle: {
    marginBottom: 20,
  },
  htmlContainer: {
    paddingHorizontal: 10,
  },
  cellContainer: {
    height: 60,
    marginTop: 10,
    marginLeft: 15,
    backgroundColor: COLOR.THEME.CEll_BG,
    flexDirection: 'row',
    borderRadius: 3,
  },
  selectOfficeContainer: {
    height: 60,
    marginTop: 10,
    marginHorizontal: 15,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1F2428',
    flexDirection: 'row',
    borderRadius: 3,
  },
  cellTitle: {
    color: COLOR.THEME.BLACK,
    fontFamily: FONT.ROBOTO,
    marginHorizontal: 15,
    fontWeight: 'bold',
    fontSize: 20,
    alignSelf: 'center',
  },
  loanOfficeText: {
    color: '#FFFFFF',
    fontFamily: FONT.ROBOTO,
    marginHorizontal: 15,
    fontWeight: 'bold',
    fontSize: 17,
    alignSelf: 'center',
  },
  cellDesc: {
    fontFamily: FONT.ROBOTO,
    color: COLOR.THEME.LIGHT_GRAY,
    paddingHorizontal: 10,
    fontSize: 14,
    marginVertical: 10,
  },
  cellTime: {
    fontFamily: FONT.ROBOTO,
    fontStyle: 'italic',
    color: COLOR.THEME.LIGHT_GRAY,
    paddingHorizontal: 10,
    fontSize: 14,
    marginBottom: 20,
    alignSelf: 'flex-end',
  },
  buttonContainer: {
    justifyContent: 'center',
    width: '100%',
    height: 120,
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
  },
  popupView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  toucableButton: {
    height: 40,
    width: '50%',
    backgroundColor: COLOR.getTheme(),
    borderRadius: 4,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonTitle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
  },
  modalOverlay: {
    height: '100%',
    width: '100%',
    backgroundColor: '#00000095',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: 'white',
    width: '90%',
    alignSelf: 'center',
    borderRadius: 4,
  },
  closeContainer: {
    height: 30,
    width: 30,
    position: 'absolute',
    top: 10,
    right: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyboardAwareL: {
    flex: 1,
  },
  modalTitle: {
    fontFamily: FONT.ROBOTO,
    alignSelf: 'center',
    marginTop: 35,
    fontSize: 17,
    fontWeight: 'bold',
  },
  modalDesc: {
    fontFamily: FONT.ROBOTO,
    alignSelf: 'center',
    marginTop: 20,
    fontSize: 14,
    paddingHorizontal: 15,
    textAlign: 'center',
    color: COLOR.THEME.LIGHT_GRAY,
  },
  modalSep: {
    height: 0.5,
    width: '90%',
    backgroundColor: COLOR.THEME.SEPARETOR,
    alignSelf: 'center',
    marginVertical: 30,
  },
  useCodeText: {
    fontFamily: FONT.ROBOTO,
    alignSelf: 'center',
    fontSize: 14,
    paddingHorizontal: 15,
    textAlign: 'center',
    color: COLOR.THEME.BLACK,
  },
  codeText: {
    fontFamily: FONT.ROBOTO,
    alignSelf: 'center',
    marginTop: 5,
    fontSize: 14,
    fontWeight: 'bold',
  },
  codeDesc: {
    fontFamily: FONT.ROBOTO,
    alignSelf: 'center',
    fontSize: 14,
    paddingHorizontal: 15,
    marginTop: 5,
    marginBottom: 30,
    textAlign: 'center',
    color: COLOR.THEME.BLACK,
  },
  closeIcon: {
    height: 30,
    width: 30,
  },
  cellImage: {
    height: 20,
    width: 20,
    alignSelf: 'center',
    marginLeft: 10,
  },
  ofcContainer: {
    minHeight: CONSTANT.SCREEN_WIDTH * 0.5,
    width: '100%',
    // marginTop: 20,
  },
  ofcSubContainer: {
    minHeight: 100,
    width: CONSTANT.SCREEN_WIDTH - 20,
    borderRadius: 4,
    // position: 'absolute',
    // bottom: 0,
    marginHorizontal: 10,
  },
  detailConatainer: {
    height: 80,
    width: CONSTANT.SCREEN_WIDTH - 140,
    right: 0,
    position: 'absolute',
  },
  ofcName: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: 'bold',
    marginTop: 10,
  },
  ofcDesignation: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'normal',
    marginTop: 5,
  },
  ofcCode: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'normal',
    marginTop: 5,
  },
  keyboardAware: {
    flex: 1,
  },
  ofcButtonContainer: {
    height: optionWidth,
    marginTop: 100,
    width: optionContainerWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
  },
  ofcSocialContaier: {
    height: optionWidth,
    width: optionContainerWidth,
    // marginTop: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
  },
  socialMargin: {
    marginTop: 100,
    width: CONSTANT.SCREEN_WIDTH - 20,
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  ofcMoreSocialContaier: {
    height: optionWidth,
    width: optionContainerWidth,
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
  },
  ofcIcon: {
    height: 20,
    width: 20,
    alignSelf: 'center',
    // marginTop: 10
  },
  ofcButton: {
    height: optionWidth,
    width: optionWidth,
    // flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: marginHori - optionWidth,
    // backgroundColor: 'red',
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
    marginVertical: 10,
  },
  ofcButtonText: {
    fontSize: 15,
    color: '#FFFFFF',
    alignSelf: 'center',
    marginTop: 10,
  },
  introContainer: {
    width: '100%',
    marginHorizontal: 10,
  },
  readMoreButton: {
    paddingRight: 15,
    paddingVertical: 10,
    justifyContent: 'center',
    alignSelf: 'flex-start',
    alignItems: 'center',
  },
  introTitle: {
    fontFamily: FONT.ROBOTO,
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
  },
  introDetail: {
    fontFamily: FONT.ROBOTO,
    fontSize: 17,
    color: '#000000',
    marginTop: 10,
  },
  readMoreText: {
    fontFamily: FONT.ROBOTO,
    fontSize: 17,
    fontWeight: 'bold',
    color: COLOR.getTheme(),
  },
  descContainer: {
    marginHorizontal: 10,
    marginVertical: 10,
    // backgroundColor: 'red',
  },
  officeTitle: {
    fontFamily: FONT.ROBOTO,
    marginVertical: 15,
    fontWeight: 'bold',
    fontSize: 17,
  },
  officerDetail: {
    fontFamily: FONT.ROBOTO,
    fontSize: 17,
    marginBottom: 20,
  },
  logo: {
    height: CONSTANT.SCREEN_WIDTH * 0.4,
    width: CONSTANT.SCREEN_WIDTH * 0.6,
    alignSelf: 'center',
    // marginTop: 10,
    marginBottom: 50,
  },
  extraScroll: {
    paddingBottom: 200,
  },
  profileImage: {
    height: 100,
    width: 100,
    marginLeft: 10,
    left: 0,
    position: 'absolute',
    top: -20,
  },
});
export default styles;
